%YAML:1.2
CPU 3D 26-way connectivity:
  
  execute: true
  
  # Tests to perform and their number of repetitions
  # ------------------------------------------------
  
  perform: 
    correctness:        true
    average:            false
    average_with_steps: true
    density:            false
    granularity:        true
    memory:             false

  correctness_tests:
    eight_connectivity_standard: false
    eight_connectivity_steps:    true
    eight_connectivity_memory:   false

  tests_number:
    average:            10
    average_with_steps: 10
    density:            10
    granularity:        5

  # List of 3D CPU CCL algorithms to test
  # -------------------------------------
  
  algorithms: 
  #  - naive_3D_UF
  #  - naive_3D_UFPC
  #  - naive_3D_TTA
  #  - naive_3D_RemSP
    - LEB_3D_UF
  #  - LEB_3D_UFPC
  #  - LEB_3D_TTA
  #  - LEB_3D_RemSP
    - RBTS_3D_UF
  #  - RBTS_3D_UFPC
  #  - RBTS_3D_TTA
  #  - RBTS_3D_RemSP
  #  - SAUF_3D_UF
  #  - SAUF_3D_UFPC
  #  - SAUF_3D_TTA
  #  - SAUF_3D_RemSP
    - SAUFpp_3D_UF
  #  - SAUFpp_3D_UFPC
  #  - SAUFpp_3D_TTA
  #  - SAUFpp_3D_RemSP
  #  - PRED_3D_UF
  #  - PRED_3D_UFPC
  #  - PRED_3D_TTA
  #  - PRED_3D_RemSP
    - PREDpp_3D_UF
  #  - PREDpp_3D_UFPC
  #  - PREDpp_3D_TTA
  #  - PREDpp_3D_RemSP
    - EPDT_3D_22c_UF

    - LSL3D_ER_UF
    - LSL3D_FSM_UF
    - LSL3D_FSM_DOUBLE_PL_UF

    - LSL3D_ER_SSE4_UF
    - LSL3D_FSM_SSE4_UF
    - LSL3D_FSM_DOUBLE_PL_SSE4_UF

  # Datasets to use for each test
  # -----------------------------
  
  # Note that perform correctness tests on labeling_NULL algorithm does not make sense
  check_datasets: ["check3D", "mitochondria", "oasis"]
  
  # List of datasets on which "Average Runtime Tests" shall be run
  average_datasets: ["mitochondria", "oasis"]
  
  # List of datasets on which "Average Runtime Tests With Steps" shall be run
  average_datasets_with_steps: ["mitochondria", "oasis"]

  parallel_average_datasets_with_steps: ["mitochondria", "oasis"]

  # List of datasets on which "Memory Tests" shall be run
  memory_datasets: ["mitochondria", "oasis"]

  # Save the results of each run test
  save_middle_tests: {average: false, average_with_steps: true, density: false, granularity: false, parallel_average_with_steps: true}

  
paths: {input: "input", output: "output"}

write_n_labels: false

color_labels: {average: false, density: false}

os: "Linux 6.0.2"
