
GPU 3D 26-way connectivity:

  execute: true
  
  # Tests to perform and their number of repetitions
  # ------------------------------------------------
  
  perform: 
    correctness:        true
    average:            true
    average_with_steps: false
    density:            false
    granularity:        true
    memory:             false
  
  correctness_tests: 
    eight_connectivity_standard: true
    eight_connectivity_steps:    true
    eight_connectivity_memory:   false
  
  tests_number: 
    average:             10 
    average_with_steps:  10
    density:             10
    granularity:         10 
  
  # List of 3D CPU CCL algorithms to test
  # -------------------------------------
  
  algorithms:
    - BUF_3D
    - BKE_3D
    - BE_3D
    - UF_3D
  
  # Datasets to use for each test
  # -----------------------------
  
  # Note that perform correctness tests on labeling_NULL algorithm does not make sense
  check_datasets: ["hilbert", "oasis", "mitochondria"]
  
  # List of datasets on which "Average Runtime Tests" shall be run
  average_datasets: ["hilbert", "oasis", "mitochondria"]
  
  # List of datasets on which "Average Runtime Tests With Steps" shall be run
  average_datasets_with_steps: ["hilbert", "oasis", "mitochondria"]
  
  # List of datasets on which "Memory Tests" shall be run
  memory_datasets: ["hilbert", "oasis", "mitochondria"]

  # Save the results of each run test
  save_middle_tests: {average: false, average_with_steps: false, density: false, granularity: false}
