%YAML:1.2
---
##########################################
# THIS IS THE YACCLAB CONFIGURATION FILE #
##########################################

# -------------------- #
#   Benchmark Tests    #
# -------------------- #

CPU 3D 26-way connectivity:
  
  execute: true
  
  # Tests to perform and their number of repetitions
  # ------------------------------------------------
  
  perform: 
    correctness:        true
    average:            false
    average_with_steps: true
    density:            false
    granularity:        false
    memory:             false

  correctness_tests: 
    eight_connectivity_standard: false
    eight_connectivity_steps:    true
    eight_connectivity_memory:   false
  
  tests_number: 
    average:            10
    average_with_steps: 10
    density:            10
    granularity:        10

  # List of 3D CPU CCL algorithms to test
  # -------------------------------------
  
  algorithms:
  #  - naive_3D_UF
  #  - naive_3D_UFPC
  #  - naive_3D_TTA
  #  - naive_3D_RemSP
    - LEB_3D_UF
  #  - LEB_3D_UFPC
  #  - LEB_3D_UF
  #  - LEB_3D_RemSP
    - RBTS_3D_UF
    #- RBTS_3D_CCA_UF
  #  - RBTS_3D_UFPC
  #  - RBTS_3D_RemSP
  #  - SAUF_3D_UF
    - SAUFpp_3D_UF
  #  - PRED_3D_UF
    - PREDpp_3D_UF
  #  - PREDpp_3D_UFPC
  #  - PREDpp_3D_TTA
  #  - PREDpp_3D_RemSP
  #  - EPDT_3D_19c_UF
   # - EPDT_3D_19c_CCA_UF
    - EPDT_3D_22c_UF
  #  - EPDT_3D_26c_UF
  #  - Rosenfeld3D_UF

    - LSL3D_ER_UF
    - LSL3D_FSM_UF
    - LSL3D_FSM_DOUBLE_PL_UF

    - LSL3D_ER_SSE4_UF
    - LSL3D_FSM_SSE4_UF
    - LSL3D_FSM_DOUBLE_PL_SSE4_UF

   # - LEB_3D_CCA_UF
   # - RBTS_3D_CCA_UF
   # - SAUFpp_3D_CCA_UF
   # - PREDpp_3D_CCA_UF
   # - EPDT_3D_22c_CCA_UF

   # - LSL3D_ER_CCA_UF
   # - LSL3D_FSM_CCA_UF
   # - LSL3D_FSM_DOUBLE_PL_CCA_UF

   # - LSL3D_ER_SSE4_CCA_UF
   # - LSL3D_FSM_SSE4_CCA_UF
   # - LSL3D_FSM_DOUBLE_PL_SSE4_CCA_UF



    #- RBTS_3D_CCA_only_UF

    #- LSL3D_ER_CCA_only_UF
    #- LSL3D_FSM_CCA_only_UF
    #- LSL3D_FSM_DOUBLE_PL_CCA_only_UF

    #- LSL3D_ER_SSE4_CCA_only_UF
    #- LSL3D_FSM_SSE4_CCA_only_UF
    #- LSL3D_FSM_DOUBLE_PL_SSE4_CCA_only_UF

  #\ Datasets to use for each test
  # -----------------------------

  # Note that perform correctness tests on labeling_NULL algorithm does not make sense
  check_datasets: ["mitochondria", "oasis"]
  
  # List of datasets on which "Average Runtime Tests" shall be run
  average_datasets: ["mitochondria", "oasis"]
  
  # List of datasets on which "Average Runtime Tests With Steps" shall be run
  average_datasets_with_steps: ["mitochondria", "oasis"]

  # List of datasets on which "Memory Tests" shall be run
  memory_datasets: ["mitochondria"]

  # Save the results of each run test
  save_middle_tests: {average: true, average_with_steps: true, density: false, granularity: false, parallel_average_with_steps: true}
  
# -------------------- #
# Additional utilities #
# -------------------- #

# Directory for input/output paths
paths: {input: "input", output: "output"}

# Save the returned number of components in output files
write_n_labels: false

# Save labeled image (TODO: remove this option from tests and add a specific tools for doing that in YACCLAB) 
color_labels: {average: false, density: false} #TODO

#os: "Linux 5.10.11-arch1-1"

##########################################
# This is the YACCLAB configuration file #
##########################################
